import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#0f1115',
  card: '#1a1d24',
  border: '#2a2f3a',
  text: '#e6e8ec',
  muted: '#9aa3b2',
  accent: '#4f8cff',
  danger: '#ff5c5c',
  ok: '#3ddc97',
  inputBg: '#11141a',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  container: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 24,
    gap: 16,
  },
  h1: { color: colors.text, fontSize: 24, fontWeight: '700' },
  h2: { color: colors.text, fontSize: 18, fontWeight: '600', marginTop: 8 },
  label: { color: colors.muted, fontSize: 13, marginBottom: 6 },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  input: {
    backgroundColor: colors.inputBg,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    color: colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  textarea: { minHeight: 120, textAlignVertical: 'top' },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  btn: {
    backgroundColor: colors.accent,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
  },
  btnGhost: {
    backgroundColor: 'transparent',
    borderColor: colors.border,
    borderWidth: 1,
  },
  btnDanger: { backgroundColor: colors.danger },
  btnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  btnTextGhost: { color: colors.text, fontWeight: '600', fontSize: 14 },
  error: { color: colors.danger, fontSize: 13 },
  success: { color: colors.ok, fontSize: 13 },
  muted: { color: colors.muted, fontSize: 13 },
  link: { color: colors.accent, fontSize: 14, fontWeight: '600' },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pillActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  pillText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  pillTextActive: { color: '#fff' },
});
